#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : gptfdisk
Version  : 1.0.9
Release  : 25
URL      : https://sourceforge.net/projects/gptfdisk/files/gptfdisk/1.0.9/gptfdisk-1.0.9.tar.gz
Source0  : https://sourceforge.net/projects/gptfdisk/files/gptfdisk/1.0.9/gptfdisk-1.0.9.tar.gz
Summary  : GPT partitioning and MBR repair software
Group    : Development/Tools
License  : GPL-2.0
Requires: gptfdisk-bin = %{version}-%{release}
Requires: gptfdisk-license = %{version}-%{release}
Requires: gptfdisk-man = %{version}-%{release}
BuildRequires : pkgconfig(ncursesw)
BuildRequires : popt-dev
BuildRequires : util-linux-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0000-add-installation.patch
Patch2: 0001-gptcurses-partially-revert-Tweaks-for-building-on-th.patch
Patch3: 0002-bypass-resolution-check.patch
Patch4: backport-popt-1.19.patch
Patch5: backport-popt-1.19-follow-up.patch

%description
Partitioning software for GPT disks and to repair MBR disks. The gdisk,
cgdisk, and sgdisk utilities (in the gdisk package) are GPT-enabled
partitioning tools; the fixparts utility (in the fixparts package) fixes
some problems with MBR disks that can be created by buggy partitioning
software.

%package bin
Summary: bin components for the gptfdisk package.
Group: Binaries
Requires: gptfdisk-license = %{version}-%{release}

%description bin
bin components for the gptfdisk package.


%package license
Summary: license components for the gptfdisk package.
Group: Default

%description license
license components for the gptfdisk package.


%package man
Summary: man components for the gptfdisk package.
Group: Default

%description man
man components for the gptfdisk package.


%prep
%setup -q -n gptfdisk-1.0.9
cd %{_builddir}/gptfdisk-1.0.9
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689793339
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}


%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
./gdisk_test.sh

%install
export SOURCE_DATE_EPOCH=1689793339
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/gptfdisk
cp %{_builddir}/gptfdisk-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gptfdisk/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1 || :
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cgdisk
/usr/bin/fixparts
/usr/bin/gdisk
/usr/bin/sgdisk

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gptfdisk/68c94ffc34f8ad2d7bfae3f5a6b996409211c1b1

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/cgdisk.8
/usr/share/man/man8/fixparts.8
/usr/share/man/man8/gdisk.8
/usr/share/man/man8/sgdisk.8
