#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gptfdisk
Version  : 1.0.4
Release  : 19
URL      : https://sourceforge.net/projects/gptfdisk/files/gptfdisk/1.0.4/gptfdisk-1.0.4.tar.gz
Source0  : https://sourceforge.net/projects/gptfdisk/files/gptfdisk/1.0.4/gptfdisk-1.0.4.tar.gz
Summary  : GPT partitioning and MBR repair software
Group    : Development/Tools
License  : GPL-2.0
Requires: gptfdisk-bin
Requires: gptfdisk-license
Requires: gptfdisk-man
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(uuid)
BuildRequires : popt-dev
Patch1: 0000-add-installation.patch
Patch2: bypass-resolution-check.patch

%description
Partitioning software for GPT disks and to repair MBR disks. The gdisk,
cgdisk, and sgdisk utilities (in the gdisk package) are GPT-enabled
partitioning tools; the fixparts utility (in the fixparts package) fixes
some problems with MBR disks that can be created by buggy partitioning
software.

%package bin
Summary: bin components for the gptfdisk package.
Group: Binaries
Requires: gptfdisk-license
Requires: gptfdisk-man

%description bin
bin components for the gptfdisk package.


%package license
Summary: license components for the gptfdisk package.
Group: Default

%description license
license components for the gptfdisk package.


%package man
Summary: man components for the gptfdisk package.
Group: Default

%description man
man components for the gptfdisk package.


%prep
%setup -q -n gptfdisk-1.0.4
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530990712
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
./gdisk_test.sh

%install
export SOURCE_DATE_EPOCH=1530990712
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/gptfdisk
cp COPYING %{buildroot}/usr/share/doc/gptfdisk/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cgdisk
/usr/bin/fixparts
/usr/bin/gdisk
/usr/bin/sgdisk

%files license
%defattr(-,root,root,-)
/usr/share/doc/gptfdisk/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man8/cgdisk.8
/usr/share/man/man8/fixparts.8
/usr/share/man/man8/gdisk.8
/usr/share/man/man8/sgdisk.8
